### ISSUE TITLE
Can't start inaetics service

### ISSUE THREAD

**Issue by fieldhof** [INAETICS/kubernetes-demo-cluster#19] opened 2015-11-18 10:38 UTC
I'm trying to get the kubernetes-demo-cluster up and running, but it fails on the inaetics service.
`journalctl -fu inaetics` gives
`Nov 18 10:21:40 controller systemd[1]: Dependency failed for INAETICS demonstrator Kubernetes services and controllers.   
Nov 18 10:21:40 controller systemd[1]: inaetics.service: Job inaetics.service/start failed with result 'dependency'.`

I checked `journalctl -u kubernetes` and it keeps saying 
`Failed to list *api.Service: Get http://127.0.0.1:10080/api/v1/services: dial tcp 127.0.0.1:10080: getsockopt: connection refused
Failed to list *api.Pod: Get http://127.0.0.1:10080/api/v1/pods?fieldSelector=spec.nodeName%3Dcontroller: dial tcp 127.0.0.1:10080: getsockopt: connection refused
Failed to list *api.Node: Get http://127.0.0.1:10080/api/v1/nodes?fieldSelector=metadata.name%3Dcontroller: dial tcp 127.0.0.1:10080: getsockopt: connection refused`

I'm using Fedora 22, Vagrant 1.7.2 and VirtualBox 4.3.32

**Comment by slintes** [comment] 2015-11-18 10:54
It looks like the Kubernetes API server is not running. Can you do a `docker ps` and check if you find a line like this:

```
85d690d7d922        gcr.io/google_containers/hyperkube:v1.0.6   "/hyperkube apiserver"   About an hour ago   Up About an hour                             k8s_kube-apiserver.12515c24_kube-apiserver-controller_kube-system_f7bf31762b6862d9b83f488c38570a43_4058cb30
```

You don't have that line, please do `docker ps -a`, check if there are failed api servers, and check if there is something useful in `docker logs <idOfFailedApiserver>`

**Comment by fieldhof** [comment] 2015-11-18 11:01
`docker ps -a` :

```
45b77b319be5        gcr.io/google_containers/hyperkube:v1.0.6   "/hyperkube apiserver"   29 seconds ago      Up 29 seconds                                k8s_kube-apiserver.12515c24_kube-apiserver-controller_kube-system_f7bf31762b6862d9b83f488c38570a43_93a3389e 
```

So it looks like it's up and running, but it started really late. There are some other containers in docker that are created 4 minutes earlier. `journalctl -fu kubernetes` doesn't give the "error" anymore, but the inaetics service has already failed.

**Comment by slintes** [comment] 2015-11-18 11:08
I currently also have the problem that the inaetics service sometimes fails because the dependencies need to long for startup, I did not find out yet how to solve that. You can manually (re-)start inaetics with `sudo systemctl start inaetics`.

**Comment by fieldhof** [comment] 2015-11-18 11:11
Just wanted to try that, thanks for the answer. Isn't there a timeout that can be set somewhere?

**Comment by slintes** [comment] 2015-11-18 11:14
Either that, or automatic retries. Need check the systemd docs what is possible and what is the best solution

**Comment by fieldhof** [comment] 2015-11-19 14:55
So today I started the kubernetes-demo again but for some reason the Api won't start
`docker ps -a` only gives:

```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
0e19dcc3686f        registry:2          "/bin/registry /etc/d"   13 minutes ago      Up 13 minutes       0.0.0.0:5000->5000/tcp   registry
```

I destroyed the VM and restarted it some times but it worked only once.
Yesterday there were at least 4 more containers even before the Api started and it took only 4-5 minutes to start up.

**Comment by slintes** [comment] 2015-11-19 17:52
thanks for the feedback, I will try to reproduce it tomorrow

**Comment by gerritbinnenmars** [comment] 2015-11-19 20:53
Hello Marc and Daan,

Did some investigation and found the following, but still not working:
1. the manifest files for k8s refer to hyperkube 1.0.6 but the download
scripts loads 1.1.0. Update to 1.1.0 in yaml files works ok.
2. kubelet expects pause 0.8.0 but the download scritp loads 2.0,
    add parameter --pod-infra-container-image="
gcr.io/google_containers/pause:2.0" to kubelet (coreos-k8s.yaml)
3. kubelet reports /registry is not managed by kubernetes (why is the
docker registry needed? Is it used at all?)
4. hostname-override=$public_ipv4 in coreos-k8s.yaml does not work, the
variable is empty

Further noticed that my internet connection is gone as soon as I use
vagrant up. Normally, I could solve this with an additional route to my
router but this does not work anymore. Not sure if related.

Hope this helps a bit.

Gerrit

**Comment by slintes** [comment] 2015-11-20 08:31
Thanks Gerrit!
1. Ah yes, forgot that we have to maintain the kubernetes version at several places now. Didn't notice it because with internet connection the old version was jut downloaded during runtime.
2. Will check what version is really used by default by k8s 1.1. From the source code it looked like pause 2.0.
3. This just means that kubelet found a docker container (which runs the registry), which was not started by k8s. The registry serves our inaetics images. So this is not an issue.
4. Oh, that's interesting. Will check if I have the same problem on my machine.

I have no problems with the internet connection, and I never needed to manually change any network settings / routes. Maybe a difference in how VirtualBox works on different host operating systems?

**Comment by slintes** [comment] 2015-11-20 10:29
ok:

1+2.:  I fixed the hyperkube version numbers in the k8s manifest files, and the pause image version in the initial download script. I recreated the cluster 3 times now without problems. I guess that the problem was, that docker tried to download the hyperkube and pause images several times in parallel, which was always a problem when using docker. Afaik that is fixed in docker 1.9, but that's not in CoreOS yet.
At least I'm not the only one, who is confused by the pause image version. Seems they are in the process of migrating to version 2.0, but not done yet: https://github.com/kubernetes/kubernetes/issues/15140

4.: $public_ipv4 is empty because the `cloud-init --from-file` call obviously does not "forward" that variable. Since we don't need it for the controller node (it does not register itself as k8s node), I just removed that parameter. It works for the worker nodes.

The only little issue I still see is that the k8s controller is restarted sometimes, probably because it is started faster than the api server, and it needs the api server. That is fixed in k8s version 1.1.2, which was released yesterday. Unfortunatly there is is no hyperkube 1.1.2 image yet.

@fieldhof: can you pull my changes, run the initial-download again, and try if the cluster is stable now for you too?

**Comment by gerritbinnenmars** [comment] 2015-11-20 12:01
Marc in the manifest files is a path /usr/share/ca-certificates is this
correct?
Op 20 nov. 2015 11:29 schreef "Marc Sluiter" notifications@github.com:

**Comment by slintes** [comment] 2015-11-20 12:10
yes:

```
core@controller ~ $ ls /usr/share/ca-certificates/
02265526.0                                                          GeoTrust_Global_CA_2.pem
024dc131.0                                                          GeoTrust_Primary_Certification_Authority.pem
03179a64.0                                                          GeoTrust_Primary_Certification_Authority_-_G2.pem
...
```

**Comment by fieldhof** [comment] 2015-11-20 14:20
@slintes The cluster seems to be stable now.

**Comment by slintes** [comment] 2015-11-20 14:21
nice, thanks for the feedback!

**Comment by gerritbinnenmars** [comment] 2015-11-20 16:05
Indeed, also working again on my system. Thanks Marc

**Comment by slintes** [comment] 2015-11-20 17:35
Perfect. Will close the issue then.

**Closed as completed by slintes** 2015-11-20 17:35 UTC
